#include "GdlLibpartXml.h"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <map>
#include <sstream>

namespace
{
    // ── the <Symbol> template, ported verbatim from ArchicadElement.cs ──────

    constexpr const char* XML_HEADER =
        R"(<?xml version="1.0" encoding="UTF-8"?>
<Symbol IsArchivable="false" IsPlaceable="true" MainGUID="CEC5B431-C761-4E74-9B8E-E1A65CE71670" MigrationValue="Normal" Owner="0" Signature="1196644685" Version="45">
<Copyright SectVersion="1" SectionFlags="0" SubIdent="0">
	<Author>Speckle Systems</Author>
	<License>
		<Type>CC BY</Type>
		<Version>4.0</Version>
	</License>
</Copyright>

<Ancestry SectVersion="1" SectionFlags="0" SubIdent="0" Template="false">
	<MainGUID>F938E33A-329D-4A36-BE3E-85E126820996</MainGUID>
	<MainGUID>103E8D2C-8230-42E1-9597-46F84CCE28C0</MainGUID>
	<MainGUID>784EAEA1-5041-4AA6-B6F4-EF263A891EE7</MainGUID>
</Ancestry>

<ParamSection SectVersion="27" SectionFlags="0" SubIdent="0">
	<ParamSectHeader>
		<AutoHotspots>false</AutoHotspots>
		<StatBits>
			<STBit_FixSize/>
		</StatBits>
		<WDLeftFrame>0</WDLeftFrame>
		<WDRightFrame>0</WDRightFrame>
		<WDTopFrame>0</WDTopFrame>
		<WDBotFrame>0</WDBotFrame>
		<LayFlags>65535</LayFlags>
		<WDMirrorThickness>0</WDMirrorThickness>
		<WDWallInset>0</WDWallInset>
	</ParamSectHeader>
	<Parameters>
		<Length Name="A">
			<Description><![CDATA["Size 1"]]></Description>
			<Fix/>
			<Value>1</Value>
		</Length>
		<Length Name="B">
			<Description><![CDATA["Size 2"]]></Description>
			<Fix/>
			<Value>1</Value>
		</Length>
		<Length Name="ZZYZX">
			<Description><![CDATA["Height"]]></Description>
			<Fix/>
			<Value>1</Value>
		</Length>
		<Boolean Name="showOnlyContourEdgesIn3D">
			<Description><![CDATA["Show Only Contour Edges In 3D"]]></Description>
			<Value>1</Value>
		</Boolean>
		<RealNum Name="map_xform">
			<Description><![CDATA["General Transformation"]]></Description>
			<ArrayValues FirstDimension="4" SecondDimension="3">
				<AVal Column="1" Row="1">1</AVal>
				<AVal Column="2" Row="1">0</AVal>
				<AVal Column="3" Row="1">0</AVal>
				<AVal Column="1" Row="2">0</AVal>
				<AVal Column="2" Row="2">1</AVal>
				<AVal Column="3" Row="2">0</AVal>
				<AVal Column="1" Row="3">0</AVal>
				<AVal Column="2" Row="3">0</AVal>
				<AVal Column="3" Row="3">1</AVal>
				<AVal Column="1" Row="4">0</AVal>
				<AVal Column="2" Row="4">0</AVal>
				<AVal Column="3" Row="4">0</AVal>
			</ArrayValues>
		</RealNum>
		<Boolean Name="AC_show2DHotspotsIn3D">
			<Description><![CDATA["Show 2D Hotspots in 3D"]]></Description>
			<Fix/>
			<Value>0</Value>
		</Boolean>
		<Length Name="ac_bottomlevel">
			<Description><![CDATA["Bottom level"]]></Description>
			<Fix/>
			<Flags>
				<ParFlg_Hidden/>
			</Flags>
			<Value>1</Value>
		</Length>
		<Length Name="ac_toplevel">
			<Description><![CDATA["Top level"]]></Description>
			<Fix/>
			<Flags>
				<ParFlg_Hidden/>
			</Flags>
			<Value>0</Value>
		</Length>
	</Parameters>
</ParamSection>

<Comment SectVersion="20" SectionFlags="0" SubIdent="0">
<![CDATA[Speckle]]>
</Comment>

<Keywords SectVersion="1" SectionFlags="0" SubIdent="0">
<![CDATA[Speckle]]>
</Keywords>

<!-- GDL SCRIPT ===== GDL SCRIPT ===== GDL SCRIPT ===== GDL SCRIPT ===== GDL SCRIPT -->

<Script_1D SectVersion="20" SectionFlags="0" SubIdent="0">
<![CDATA[)";

    constexpr const char* XML_MID =
        R"(
]]>
</Script_1D>

<!-- GDL SCRIPT ===== GDL SCRIPT ===== GDL SCRIPT ===== GDL SCRIPT ===== GDL SCRIPT -->

<Script_3D SectVersion="20" SectionFlags="0" SubIdent="0">
<![CDATA[
!
! 3D Script (Generated by Speckle Connector)
!

defaultResolution = 36
RESOL defaultResolution

hiddenProfileEdge = 0
hiddenBodyEdge = 0
smoothBodyEdge = 0
visibleBodyEdge = 262144

IF (GLOB_CONTEXT % 10 >= 2 AND GLOB_CONTEXT % 10 <= 4) AND showOnlyContourEdgesIn3D <> 0 THEN
	hiddenProfileEdge = 1
	hiddenBodyEdge = 1
	smoothBodyEdge = 2
ENDIF

!

RESOL defaultResolution

XFORM map_xform[1][1], map_xform[2][1], map_xform[3][1], map_xform[4][1],
	map_xform[1][2], map_xform[2][2], map_xform[3][2], map_xform[4][2],
	map_xform[1][3], map_xform[2][3], map_xform[3][3], map_xform[4][3]

)";

    constexpr const char* XML_FOOTER =
        R"(
DEL TOP
]]>
</Script_3D>

<!-- GDL SCRIPT ===== GDL SCRIPT ===== GDL SCRIPT ===== GDL SCRIPT ===== GDL SCRIPT -->

<Script_2D SectVersion="20" SectionFlags="0" SubIdent="0">
<![CDATA[
!
cutPlaneHeight	= (GLOB_CSTORY_ELEV + GLOB_CUTPLANES_INFO[1]) - GLOB_HSTORY_ELEV
cutHeight = 0.01
iCutPlanes = 1

for i = 1 to iCutPlanes
	put cutPlaneHeight + (i-1) * cutHeight
next i

for i = 0 to iCutPlanes
	put 1+32,		! method
		2,				! parts
		1,				! cutFillIndex
		1,				! cutFillFgPen
		1,				! cutFillBgPen
		0.0,			! cutFillOrigoX
		0.0,			! cutFillOrigoY
		0.0,			! cutFillDirection
		1,				! cutLinePen
		1,				! cutLineType
		1,				! projectedFillIndex
		1,				! projectedFillFgPen
		1,				! projectedFillBgPen
		0.0,			! projectedFillOrigoX
		0.0,			! projectedFillOrigoY
		0.0,			! projectedFillDirection
		1,				! projectedLinePen
		1				  ! projectedLineType
next i

project2{4} 3, 270,
	0,			! useTransparency
	0,			! statusParts
	iCutPlanes,	! numCutplanes
	get (nsp)
]]>
</Script_2D>

</Symbol>)";

    // ── formatting helpers (invariant, dot decimal separator) ────────────────

    // C# "{0:F6}" — fixed 6 decimals.
    std::string F6(double v)
    {
        char buf[64];
        std::snprintf(buf, sizeof(buf), "%.6f", v);
        return buf;
    }

    // C# "0.####" — up to 4 decimals, trailing zeros trimmed, no decimal point when integral.
    std::string Coef(double v)
    {
        char buf[64];
        std::snprintf(buf, sizeof(buf), "%.4f", v);
        std::string s = buf;
        while (!s.empty() && s.back() == '0')
            s.pop_back();
        if (!s.empty() && s.back() == '.')
            s.pop_back();
        return s.empty() ? "0" : s;
    }

    void AppendMaterial(std::string& out, const GdlLibpartXml::XmlMaterial& m)
    {
        // Type 1 is the simple definition (n=9): the specular colour and emission
        // parameters are constants or derived, so emission cannot be set. Only the
        // general definition (type 0, n=16) accepts them — so stay on type 1 unless
        // this material actually emits, and existing output is unchanged.
        const bool general = m.hasEmission;
        out += "DEFINE MATERIAL \"" + m.name + "\" " + (general ? "0" : "1") + ",\n";
        out += "        " + Coef(m.r) + ", " + Coef(m.g) + ", " + Coef(m.b) + ",! surface RGB [0.0..1.0]\n";
        out += "        " + Coef(m.ambient) + ", " + Coef(m.diffuse) + ", " + Coef(m.specular) + ", " +
               Coef(m.transparent) + ", ! ambient, diffuse, specular, transparent [0..1]\n";
        out += "        " + std::to_string(m.shining) + ", ! shining [0..100]\n";
        out += "        " + std::to_string(m.transparencyAttenuation) +
               (general ? "," : " ") + " ! transparency attenuation [0..4]\n";
        if (general)
        {
            // The general form requires specular RGB before the emission triplet;
            // white is the neutral choice the simple form already implies.
            out += "        1, 1, 1, ! specular RGB [0.0..1.0]\n";
            out += "        " + Coef(m.emissionR) + ", " + Coef(m.emissionG) + ", " + Coef(m.emissionB) +
                   ", ! emission RGB [0.0..1.0]\n";
            out += "        " + Coef(m.emissionAttenuation) + " ! emission attenuation [0..65.5]\n";
        }
        out += "\n";
    }

    // Mesh → VERT/EDGE/PGON body, porting ArchicadMesh's edge dedup and signed
    // 1-based edge references (the sign carries the polygon loop orientation).
    struct GdlBody
    {
        std::string verts;
        std::vector<std::pair<int, int>> edges; // start, end (0-based verts)
        std::map<std::pair<int, int>, int> edgeLookup;
        std::vector<int> edgeUseCount;
        std::string pgons;

        int AddEdge(int start, int end)
        {
            const auto key = std::make_pair(std::min(start, end), std::max(start, end));
            auto it = edgeLookup.find(key);
            if (it != edgeLookup.end())
            {
                const int index = it->second;
                edgeUseCount[index]++;
                // Ported as-is from ArchicadMesh.AddEdge: a shared edge beyond the
                // first two gets duplicated instead of reused (smooth/hard edge
                // handling placeholder in the original).
                if (static_cast<int>(edges.size()) > 2)
                {
                    edges.emplace_back(start, end);
                    edgeUseCount.push_back(1);
                    return static_cast<int>(edges.size());
                }
                return edges[index].first == start ? index + 1 : -(index + 1);
            }
            edgeLookup[key] = static_cast<int>(edges.size());
            edges.emplace_back(start, end);
            edgeUseCount.push_back(1);
            return static_cast<int>(edges.size());
        }

        void AddPolygon(const std::vector<int>& faceVertices, const std::string& materialName)
        {
            std::vector<int> edgeRefs;
            edgeRefs.reserve(faceVertices.size());
            for (size_t j = 0; j < faceVertices.size(); j++)
            {
                const int start = faceVertices[j];
                const int end = faceVertices[(j + 1) % faceVertices.size()];
                edgeRefs.push_back(AddEdge(start, end));
            }

            pgons += "MATERIAL \"" + materialName + "\"\n";
            pgons += "PGON " + std::to_string(edgeRefs.size()) + ", 0, -1";
            int count = 1;
            for (const int index : edgeRefs)
            {
                if (count % 10 == 0)
                {
                    pgons += ",\n" + std::to_string(index);
                }
                else
                {
                    pgons += ", " + std::to_string(index);
                }
                count++;
            }
            pgons += "\n";
        }
    };

    void AppendMesh(std::string& out, const GdlLibpartXml::XmlMesh& mesh)
    {
        GdlBody body;

        for (size_t i = 0; i + 2 < mesh.vertices.size(); i += 3)
        {
            body.verts += "VERT " + F6(mesh.vertices[i]) + ", " + F6(mesh.vertices[i + 1]) + ", " +
                          F6(mesh.vertices[i + 2]) + "\n";
        }

        const int vertexCount = static_cast<int>(mesh.vertices.size() / 3);
        size_t i = 0;
        while (i < mesh.faces.size())
        {
            int faceSize = mesh.faces[i++];
            if (faceSize < 3)
                faceSize += 3; // legacy 0/1 tri/quad codes
            if (i + static_cast<size_t>(faceSize) > mesh.faces.size())
                break; // malformed tail — stop rather than read out of bounds

            std::vector<int> face(mesh.faces.begin() + i, mesh.faces.begin() + i + faceSize);
            i += faceSize;

            bool valid = true;
            for (const int v : face)
            {
                if (v < 0 || v >= vertexCount)
                {
                    valid = false;
                    break;
                }
            }
            if (!valid)
                continue;

            if (faceSize == 3)
            {
                body.AddPolygon(face, mesh.materialName);
            }
            else
            {
                // Fan-triangulate ngons so every PGON is planar (the desktop
                // service triangulated via MeshTriangulationHelper; a fan is
                // equivalent for convex faces, which display meshes are in practice).
                for (int t = 1; t + 1 < faceSize; t++)
                {
                    body.AddPolygon({ face[0], face[t], face[t + 1] }, mesh.materialName);
                }
            }
        }

        out += body.verts;
        out += "\n";
        for (const auto& e : body.edges)
        {
            out += "EDGE " + std::to_string(e.first + 1) + ", " + std::to_string(e.second + 1) + ", -1, -1, 1\n";
        }
        out += "\n";
        out += body.pgons;
        out += "\nBODY 4\nBASE\n\n";
    }
}

namespace GdlLibpartXml
{
    std::string SanitizeName(const std::string& input)
    {
        const std::string invalid = "<>:\"/\\|?*";
        std::string out;
        out.reserve(input.size());
        for (const char c : input)
            out.push_back(invalid.find(c) != std::string::npos ? '_' : c);
        return out;
    }

    std::string BuildSymbolXml(const std::vector<XmlMaterial>& materials, const std::vector<XmlMesh>& meshes)
    {
        std::string out;
        out.reserve(64 * 1024);
        out += XML_HEADER;
        for (const auto& m : materials)
            AppendMaterial(out, m);
        out += XML_MID;
        for (const auto& mesh : meshes)
            AppendMesh(out, mesh);
        out += XML_FOOTER;
        return out;
    }
}
