# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Archicad

on:
  pull_request:


permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: Build
        run: ./build.ps1
